name: todo_list
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_signin_button: ^2.0.0
  date_picker_timeline: ^1.2.3
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  google_sign_in: ^5.4.2
  validatorless: ^1.2.1
  intl: ^0.17.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
