// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA863V-25fRTv52lUXPZvJQhZ6DlRdYL80',
    appId: '1:650685959672:web:411a05c5ca5d9dd012da0d',
    messagingSenderId: '650685959672',
    projectId: 'todolist-34e9a',
    authDomain: 'todolist-34e9a.firebaseapp.com',
    storageBucket: 'todolist-34e9a.appspot.com',
    measurementId: 'G-6H8TFFL912',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqUQ6kmDL3u8UFi2II8quxsHz_76wK8HU',
    appId: '1:650685959672:android:f4c0019b858d95e512da0d',
    messagingSenderId: '650685959672',
    projectId: 'todolist-34e9a',
    storageBucket: 'todolist-34e9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8EvwpH_ry679g2VkZ_9V7nEDFnXQX4YI',
    appId: '1:650685959672:ios:ea99d0545c74248b12da0d',
    messagingSenderId: '650685959672',
    projectId: 'todolist-34e9a',
    storageBucket: 'todolist-34e9a.appspot.com',
    iosClientId: '650685959672-t3lurkm9mmpqug7v4prq5sapkjdhf2ff.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8EvwpH_ry679g2VkZ_9V7nEDFnXQX4YI',
    appId: '1:650685959672:ios:ea99d0545c74248b12da0d',
    messagingSenderId: '650685959672',
    projectId: 'todolist-34e9a',
    storageBucket: 'todolist-34e9a.appspot.com',
    iosClientId: '650685959672-t3lurkm9mmpqug7v4prq5sapkjdhf2ff.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );
}
